//
//  ABMKNetworkRequestOperation.h
//  Audible
//
//  Created by Esposito, Timothy on 8/22/16.
//  Copyright © 2016 Audible, Inc. All rights reserved.
//

@class AMZRequestSigningPair;

@import Foundation;

/**
 *  The error domain for all custom errors generated by ABMKNetworkRequestOperation
 */
extern NSString *const ABMKNetworkRequestDomain;

/**
 *  All of the possible custom errors generated by ABMKNetworkRequestOperation
 */
typedef NS_ENUM(NSUInteger, ABMKNetworkRequestErrorCode) {

    /**
     * The operation failed to properly generate a remote request. See the value of the NSLocalizedDescriptionKey for information on why validation failed.
     */
    ABMKNetworkRequestValidationFailed = 1,

    /**
     * The JSON returned by the service has the wrong top level type. See the value of the NSLocalizedDescriptionKey in the user info dictionary for more information.
     */
    ABMKNetworkRequestErrorCodeIncorrectResponseType = 2,

    /**
     * The response received was something other than a 200 OK. See the value of the NSLocalizedDescriptionKey in the user info dictionary for more information.
     */
    ABMKNetworkRequestErrorCodeInvalidResponseStatus = 3,

    /**
     * The network request failed. See the value of the NSLocalizedDescriptionKey in the user info dictionary for more information, and the NSUnderlyingErrorKey for the actual error returned by the NSURLSessionDataTask.
     */
    ABMKNetworkRequestErrorCodeNetworkError = 4,

    /**
     *  The parser failed to decode the JSON into objects. See the value of the NSLocalizedDescriptionKey in the user info dictionary for more information, and the NSUnderlyingErrorKey for the actual error returned by the NSURLSessionDataTask.
     */
    ABMKNetworkRequestErrorCodeJSONParsingError = 5,

    /**
     *  The request signing failed. See the value of the NSLocalizedDescriptionKey in the user info dictionary for more information.
     */
    ABMKNetworkRequestErrorCodeRequestSigningFailed = 6,

    /**
     *  The response model validation failed. See the value of the NSLocalizedDescriptionKey in the user info dictionary and the ABMKContentInsertionModelValidationFailureUserInfoKey for information, including the fields that failed validation.
     */
    ABMKNetworkRequestErrorCodeValidationFailed = 7
};

/**
 * A nice generic network request operation class that can handle mostly anything.
 * This class must be subclassed and implement the mandatory methods.
 */
@interface ABMKNetworkRequestOperation : NSOperation

/*! @abstract Use a designated initializer */
- (instancetype)init NS_UNAVAILABLE;

/**
 * The designated initializer
 */
- (instancetype)initWithSession:(NSURLSession *)session requestSigningPair:(AMZRequestSigningPair *)signingPair NS_DESIGNATED_INITIALIZER;

@end
